### ISSUE TITLE
Missing free 5 migration guide

### ISSUE THREAD

**Issue by bitc** [ekmett/free#167]
I am using the [ede](https://hackage.haskell.org/package/ede) library. It compiles fine with free 4.12.4, but with free 5 it doesn't compile:

```
src/Text/EDE/Internal/Types.hs:151:17: error:
    • No instance for (Data.Functor.Classes.Eq1 ExpF)
        arising from the second field of ‘Template’ (type ‘Exp Delta’)
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Eq Template)
    |
151 |     } deriving (Eq)
    |                 ^^
```

I would like to send a pull request to fix ede to work with the new version of free but it's not clear how to fix it.

These are the relevant lines I believe:

https://github.com/brendanhay/ede/blob/master/src/Text/EDE/Internal/Types.hs#L190

```haskell
-- | A parsed and compiled template.
data Template = Template
    { _tmplName :: !Text
    , _tmplExp  :: !(Exp Delta)
    , _tmplIncl :: HashMap Id (Exp Delta)
} deriving (Eq)

-- ✂ ---------------

data ExpF a
    = ELit  !Value
    | EVar  !Var
    | EFun  !Id
    | EApp  !a  !a
    | ELet  !Id !a !a
    | ECase !a  [Alt a]
    | ELoop !Id !a !a
    | EIncl !Text
      deriving (Eq, Show, Functor)

type Exp = Cofree ExpF
```

Thank you

**Comment by treeowl** [comment]
The problem you're seeing was caused by [this commit](https://github.com/ekmett/free/commit/f6d7d13ae75fadc8bcde7044e272fe2783d1f472), where the constraint on the `Eq` instance changed. I'm not sure that change was a good idea; I don't see why it was made.

You can use [`deriving-compat`](https://hackage.haskell.org/package/deriving-compat-0.4.1/docs/Data-Eq-Deriving.html) to derive an `Eq1` instance for `ExpF` using `TemplateHaskell`, or you can write the instance yourself. Something like this:

```haskell
instance eq1 ExpF where
  liftEq _eq (ELit x) (ELit y) = x == y
  liftEq _eq (EVar x) (EVar y) = x == y
  liftEq _eq (EFun x) (EFun y) = x == y
  liftEq eq (EApp x y) (EApp p q) = eq x p && eq y q
  liftEq eq (ELet x y z) (ELet p q r) = x == p && eq y q && eq z r
  liftEq eq (ECase x ys) (ECase p qs) = eq x p && liftEq (liftEq eq) ys qs
  liftEq eq (ELoop x y z) (ELoop p q r) = x == p && eq y q && eq z r
  liftEq _eq (EIncl x) (EIncl y) = x == y
  liftEq _ _ _ = False
```

**Comment by RyanGlScott** [comment]
If Template Haskell isn't to your liking, you can also use the `Generic1`-based functions in [`Data.Functor.Classes.Generic`](https://github.com/ekmett/transformers-compat/blob/727e112b18eb47815e6ecd8d8c3e640f3e0a7fcf/generics/Data/Functor/Classes/Generic/Internal.hs) from `transformers-compat-0.6`.

In any case, the issue here isn't with `free`, but rather the classes with `Data.Functor.Classes`, which are used in many packages. I don't feel like putting a guide in `free` is warranted since, well, we could just as well put anywhere.
